CREATE TABLE IF NOT EXISTS `OBSERVATORY` (
  `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `SHORT_LABEL` varchar(40) NULL,
  `LONG_LABEL` varchar(256) NULL,
  `DESCRIPTION` text NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `DRAINAGE_BASIN` (
  `ID` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` varchar(40) NULL,
  `OBSERVATORY_ID` int(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT FOREIGN KEY (OBSERVATORY_ID) references OBSERVATORY(ID)
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;